-- Note: this is the SQL definition, as needed for the Supabase database. You can paste this into the SQL editor when creating a table
-- Authentication is directly handled by the Supabase, so no need to store user information
-- Groups table
create table
  public.groups (
    id bigint generated by default as identity,
    name text null,
    prompt text null,
    last_prompt_updated bigint null,
    owner text not null,
    mosaic json null,
    constraint groups_pkey primary key (id),
    constraint groups_id_key unique (id)
  ) tablespace pg_default;

-- Groups belonging to a user table
create table
  public.usersgroups (
    "user" text not null,
    active_drawing_svg text null,
    active_drawing_json jsonb null,
    group_id bigint not null,
    constraint usersgroups_pkey primary key ("user", group_id),
    constraint public_usersgroups_group_id_fkey foreign key (group_id) references groups (id)
  ) tablespace pg_default;