interface PromptObject {
    [key: number]: string;
}

export const Prompts: PromptObject = {
    1: "Draw your dream vacation",
    2: "Depict your spirit animal",
    3: "Create a fantasy creature",
    4: "Design your dream home",
    5: "Illustrate your morning routine from waking up to walking out the door",
    6: "Draw a diary of your entire day. Highlight the mundane moments",
    7: "Depict a spacecraft venturing into uncharted territories of the cosmos",
    8: "Depict an epic space battle between rival factions or alien species",
    9: "Create a doodle inspired by a conversation you had today",
    10: "Draw your current mood using only colors and shapes",
    11: "Create a doodle inspired by a memory from your childhood",
    12: "Sketch a scene from your day using only your non-dominant hand",
    13: "Sketch a scene from your day as if it were a page from a comic book",
    14: "Create a doodle inspired by a recent news headline",
    15: "Sketch a scene from your day using only one continuous line",
    16: "Draw a place you visited today from memory",
    17: "Illustrate a new word or phrase you learned today (or recently)",
    18: "Sketch your mood throughout the day in a graph",
    19: "Draw the last thing you did last night before going to bed",
    20: "Draw the ugliest landscape you've ever seen",
    21: "Create a country made up of your favorite places",
    22: "Illustrate a scene from a memorable trip you took",
    23: "Draw the place you would go if you had two weeks to live",
    24: "Draw yourself as a superhero saving the city from a supervillain",
    25: "Illustrate your dream vacation spot",
    26: "Create a fantastical landscape inspired by your favorite song",
    27: "Depict your dream future, including your ideal home, career, etc",
    28: "Show us the place you hate the most",
    29: "Depict your ideal reading nook, surrounded by all your favorite books",
    30: "Draw a picture of the celebrity you would most like to meet",
    31: "Sketch a brief overview of your plan for tomorrow",
}